### ISSUE TITLE
Bignum serialization not working properly

### ISSUE THREAD

**Issue by smtlaissezfaire** [mojombo/bert#1]
I know that none of the docs say that BERT supports Bignum, but I've noticed the following code:

http://github.com/mojombo/bert/blob/master/lib/bert/encode.rb#L25

AND

http://github.com/mojombo/bert/blob/master/lib/bert/encode.rb#L80

Just to prove it:

http://gist.github.com/219222

**Comment by mojombo** [comment]
fix bignum encoding. closed by 843a50c1a5f26f809f66e462b8299da75b43bc0d.

**Comment by smtlaissezfaire** [comment]
Great!  Thanks.
